### ISSUE TITLE
Backend breaks sigma-cli

### ISSUE THREAD

**Issue by seanthegeek** [redsand/pySigma-backend-hawk#1]
After installing the backend, and sigma command fails

```text
Traceback (most recent call last):
  File "/home/sean/.local/bin/sigma", line 5, in <module>
    from sigma.cli.main import main
  File "/home/sean/.local/lib/python3.11/site-packages/sigma/cli/main.py", line 3, in <module>
    from .list import list_group
  File "/home/sean/.local/lib/python3.11/site-packages/sigma/cli/list.py", line 6, in <module>
    plugins = InstalledSigmaPlugins.autodiscover()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sean/.local/lib/python3.11/site-packages/sigma/plugins.py", line 65, in autodiscover
    backends = cls._discover_module_directories(sigma.backends, "backends", include_backends)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sean/.local/lib/python3.11/site-packages/sigma/plugins.py", line 53, in _discover_module_directories
    imported_module = importlib.import_module(module.name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sean/.local/lib/python3.11/site-packages/sigma/backends/hawk/__init__.py", line 1, in <module>
    from .hawk import hawkBackend
  File "/home/sean/.local/lib/python3.11/site-packages/sigma/backends/hawk/hawk.py", line 6
    from sigma.pipelines.hawk import # TODO: add pipeline imports or delete this line
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax
```

**Comment by redsand** [comment]
Closing this issue — it has been resolved through a significant rewrite of the backend.

**Original problem:** The cookiecutter template left a broken import line that caused a `SyntaxError` when sigma-cli tried to auto-discover the plugin:
```python
from sigma.pipelines.hawk import # TODO: add pipeline imports or delete this line
```

**Resolution:** The backend has been completely rewritten across multiple commits (2025-04-22 through 2026-02-22). The current `hawk.py` is a fully functional `hawkBackend(TextQueryBackend)` (~31KB) with:

- ✅ Proper, valid Python imports — no syntax errors
- ✅ Full detection rule conversion with field mapping and logsource enrichment
- ✅ Correlation rule support (event_count, value_count, sum, avg, percentile, median)
- ✅ Value expression and field-reference comparison support
- ✅ GCP proto payload field mappings
- ✅ Integrity level normalization (SID-to-level mapping)
- ✅ Hash field aliasing (sha256 → file_hash_sha256, etc.)

The backend now works as expected with sigma-cli.
